name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  compared-branch-name:
    required: true
    description: 'The name of the branch to compare to'
  compared-script:
    required: true
    description: 'The script to run to compare the branches'
outputs:
  isResultSame:
    description: 'Whether the result of the script is the same'
runs:
  using: 'node16'
  main: 'dist/index.js'
